### ISSUE TITLE
I made a Svelte port!

### ISSUE THREAD

**Issue by thislooksfun** [Tarptaeya/repo-card#11]
If anyone wants a responsive native Svelte version of this project, [I made one](https://github.com/thislooksfun/svelte-repo-card)!

**Comment by tarptaeya** [comment]
Thanks @thislooksfun!

You can also create a PR to add your project in "Related projects" section of the README here...

**Comment by thislooksfun** [comment]
I might be blind, but it seems that there is no "Related projects" section in the README.

**Comment by tarptaeya** [comment]
There is now... ;-)

**Comment by thislooksfun** [comment]
So there is! And thus, #13 has been created.
