### ISSUE TITLE
modify style

### ISSUE THREAD

**Issue by salicius** [Tarptaeya/repo-card#12]
Hi, how can I modify style of cards ? Seems it set only in repo-card.js

**Comment by tarptaeya** [comment]
Hey, you cannot modify the style of cards because it is made to look like github cards...Are you asking about applying dark mode style to cards?

**Comment by salicius** [comment]
Yes, dark mode and also border radius

**Comment by tarptaeya** [comment]
Hi @salicius dark theme (`dark-default`) is now supported! 🎉
