### ISSUE TITLE
Live demo dark style is broken

### ISSUE THREAD

**Issue by ferrybig** [Tarptaeya/repo-card#15]
### Steps:
1. Go to https://anmolgautam.com/repo-card/

### Expected:
Both the light and dark theme cards

### Actual:
The dark theme card fails to load an emits the following error in the code:
```
 Uncaught (in promise) TypeError: theme is undefined
    <anonymous> https://anmolgautam.com/repo-card/repo-card.js:50
    async* https://anmolgautam.com/repo-card/repo-card.js:1
```

**Comment by tarptaeya** [comment]
fixed by #20
