### ISSUE TITLE
Handle rate limits

### ISSUE THREAD

**Issue by linusg** [Tarptaeya/repo-card#8]
When the GitHub API decides it's time to rate limit a certain IP address, it still returns a valid JSON reponse but with a HTTP 403 status code:

```json
{
    "message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url":"https://developer.github.com/v3/#rate-limiting"
}
```

As a result, the repo card has `undefined`s all over the place :(

![image](https://user-images.githubusercontent.com/19366641/87032441-88c81000-c1dc-11ea-9056-6559df55279d.png)

Would be nice to catch this and maybe apply a CSS class to the container so the cards can be hidden / replaced with something meaningful.

**Comment by tarptaeya** [comment]
Fixed!
